### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by billie2jean** [gangweiX/IGEV#92]
I want to train in KITTI, but it's wrong with AssertionError like this:
`2024-12-13 08:05:11,169 INFO     [helpers.py:188] Loading pretrained weights from url (https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-weights/mobilenetv2_100_ra-b33bc2c4.pth)
Parameter Count: 12598114
Traceback (most recent call last):
  File "train_stereo.py", line 239, in <module>
    train(args)
  File "train_stereo.py", line 124, in train
    train_loader = datasets.fetch_dataloader(args)
  File "/home/cvgroup/yyy/IGEV-main/IGEV-Stereo/core/stereo_datasets.py", line 312, in fetch_dataloader
    new_dataset = KITTI(aug_params)
  File "/home/cvgroup/yyy/IGEV-main/IGEV-Stereo/core/stereo_datasets.py", line 252, in __init__
    assert os.path.exists(root)
AssertionError
`
I dont know how this mistake happen

**Comment by gangweiX** [comment]
For core/stereo_datasets.py, root='/data/KITTI/KITTI_2015' should be set to your own KITTI dataset path.
<img width="754" alt="image" src="https://github.com/user-attachments/assets/8dd6d121-a229-4608-b965-2e24d85add56" />

**Comment by billie2jean** [comment]
Thank you! I revisited the path based on your prompt and I noticed that the case of the dataset folder is not uniform, which is what is causing this issue.
